---
### PATHS
DATA_DIR: 'D:/DataStorage'

### FILTERS
# basic
COLUMNS: ['PRODUCT_ID','FILE_NAME_SPECIFICATION','RATIONALE_DESC','OBSERVATION_START_TIME', 'MAP_SCALE','MAP_PROJECTION_TYPE', 
        'PROJECTION_CENTER_LATITUDE' , 'PROJECTION_CENTER_LONGITUDE', 'SOLAR_LONGITUDE', 
        'CORNER1_LATITUDE','CORNER1_LONGITUDE','CORNER2_LATITUDE','CORNER2_LONGITUDE',
        'CORNER3_LATITUDE','CORNER3_LONGITUDE','CORNER4_LATITUDE','CORNER4_LONGITUDE']
MIN_LAT: 78

# advanced
SCALE: 0.25
KEYWORDS: ['scarp', 'boundary', 'layered deposits', 'exposure']
SEASON: 'Northern summer'

# Darwin
API_KEY: "qCzK_ya.6BNmgaY92_wxTpWEojTSFv_GHi4HVkWU"
DSET: "SCARPS"
TEAM: "Planetary Geodesy"
